services:
  - type: web
    name: agrifriend-backend
    runtime: python
    rootDir: agrifriend-backend
    buildCommand: pip install -r requirements.txt && python -c "from langchain_huggingface import HuggingFaceEmbeddings; HuggingFaceEmbeddings(model_name='all-MiniLM-L6-v2', model_kwargs={'device': 'cpu'})"
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: WEATHER_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false